### ISSUE TITLE
Core Profile TCK is configured to use Arquillian servlet runner, but servlet is not required for Core Profile

### ISSUE THREAD

**Issue by brideck** [jakartaee/platform-tck#1096]
The new EE10 Core Profile TCK is currently configured to use the Arquillian servlet runner to drive test execution.

As an example, here's Wildfly's TCK runner [Note: Open Liberty is also currently configured similarly]:
Servlet dependency: https://github.com/jakartaredhat/wf-core-tck-runner/blob/8571693aa968b97cf5961dc157a3b0402eff0ce8/core-tck/pom.xml#L87
Arquillian configuration: https://github.com/jakartaredhat/wf-core-tck-runner/blob/8571693aa968b97cf5961dc157a3b0402eff0ce8/core-tck/src/test/resources/arquillian.xml#L32

Unfortunately, since Servlet is not required for Core Profile, this is going to be a problem for servers that are only seeking to implement Core Profile.  These tests need to either be configured to run in a different way (not sure what our options might be) or rewritten so as not to require Arquillian's servlet runner.

If servlet is removed from the server under test, the majority of the TCK will fail with exceptions like this:
```
java.lang.IllegalStateException: Error launching request at http://localhost:9080/JsonbApplicationIT/ArquillianServletRunnerEE9?outputMode=serializedObject&className=ee.jakarta.tck.core.jsonb.JsonbApplicationIT&methodName=testInjectCustomProvider. No result returned
        at org.jboss.arquillian.protocol.servlet5.ServletMethodExecutor.executeWithRetry(ServletMethodExecutor.java:131)
        at org.jboss.arquillian.protocol.servlet5.ServletMethodExecutor.invoke(ServletMethodExecutor.java:97)
        ...
```

**Comment by arjantijms** [comment]
This probably requires creating an implementation of `org.jboss.arquillian.container.test.spi.client.protocol.Protocol<T>` that uses Jakarta REST instead of Jakarta Servlet.

The implementation of the Servlet 5 protocol is here: https://github.com/arquillian/arquillian-core/tree/master/protocols/servlet-jakarta

**Comment by starksm64** [comment]
Servlet is the only currently viable protocol for a testsuite that make use of RESTful invocations in Jakarta EE at the moment. This is essentially a test harness detail.

**Comment by starksm64** [comment]
> This probably requires creating an implementation of `org.jboss.arquillian.container.test.spi.client.protocol.Protocol<T>` that uses Jakarta REST instead of Jakarta Servlet.
> 
> The implementation of the Servlet 5 protocol is here: https://github.com/arquillian/arquillian-core/tree/master/protocols/servlet-jakarta

The Arquillian protocol is about how to package the tests and execute the test. The test themselves still make use of the invocation protocol for the target technology. In the case of RESTful, it creates a war deployment for the test, but does not deploy the test class to the server. It runs the tests remotely and these use the servlet protocol to invoke the rest endpoints. Without defining a pluggable invocation stack into RESTful, there is no way to deal with this generically.

**Comment by starksm64** [comment]
Brian mentioned there were tests passing without a servlet container, and maybe they are using that mode, in which case, yes, the Arquillian container adaptor would be responsible for invoking the test and collecting the result. I'll look for which tests are using testable=true to see what they are doing.

**Comment by starksm64** [comment]
So I have looked through many of the RESTful tests, and there are many tests that don't even require a container of any type as they are just testing essentially client side or rest api implementation details in TestNG unit tests.

But every test with a deployment (including those with testable=true) ends up invoking the ee.jakarta.tck.ws.rs.common.JAXRSCommonClient#invoke() method with various properties set. This ultimately invokes a org.apache.commons.httpclient.HttpConnection to execute an http method request, so there is a hard coded requirement for an http endpoint representation of a RESTful endpoint.

**Comment by brideck** [comment]
Yes, and I've done some more digging into what we're seeing/doing on our end.  Apparently, we've restricted use of the servlet APIs (which is why we were able to see the problem with that specific set of RESTful tests) but are still using our servlet implementation internally for REST, so the tests that need it are still using it.

The reason the Arquillian servlet runner runs into difficulty for the Core Profile TCK tests referenced in this issue is that the server-side runner class (https://github.com/arquillian/arquillian-core/blob/master/protocols/servlet/src/main/java/org/jboss/arquillian/protocol/servlet/runner/ServletTestRunner.java) is unable to resolve its usage of the servlet API and fails to initialize.

**Comment by arjantijms** [comment]
> the server-side runner class (https://github.com/arquillian/arquillian-core/blob/master/protocols/servlet/src/main/java/org/jboss/arquillian/protocol/servlet/runner/ServletTestRunner.java) is unable to resolve its usage of the servlet API and fails to initialize.

So maybe there's two potential solutions here:

1. Introduce a REST protocol that doesn't use a ServletTestRunner but a JakartaRESTTestRunner
2. Ask Helidon to implement "just enough" Servlet API to be able to get ServletTestRunner running

**Comment by jhanders34** [comment]
To give an update to this issue:  https://github.com/arquillian/arquillian-core/pull/407 was merged into arquillian yesterday and work is happening to make a new 1.7.0 Alpha11 release of Arquillian.  Wildfly team is working on making updates to their Arquillian plugin to make use of the new REST protocol and Liberty has logic already to make use of it with PR https://github.com/OpenLiberty/liberty-arquillian/pull/118.  Brian will be testing with this new version early next week.  When the Arquillian 1.7.0 Alpha11 release is available, the liberty plugin will switch to that and remove the forked version of the REST protocol from the liberty arquillian repo.  Likely when that is all done a new 2.1 version of the liberty arquillian plugin will be created pending results from Brian's run of Core TCK.

**Comment by starksm64** [comment]
An Arquillian 1.7.0 Alpha11 release has been published to maven central.

**Comment by jhanders34** [comment]
> An Arquillian 1.7.0 Alpha11 release has been published to maven central.

It appears to not have made it to maven central yet.

**Comment by jhanders34** [comment]
> > An Arquillian 1.7.0 Alpha11 release has been published to maven central.
> 
> It appears to not have made it to maven central yet.

Looks like it is there now.

**Comment by jhanders34** [comment]
https://github.com/arquillian/arquillian-core/issues/418 issue created which may warrant having a 1.7.0.Alpha12 release with the fix for it.

**Comment by starksm64** [comment]
I'll do the 1.7.0.Alpha12 release today.

**Comment by starksm64** [comment]
The release has been created and pushed to maven central. It will take some time to propagate.
https://github.com/arquillian/arquillian-core/releases/tag/1.7.0.Alpha12

**Comment by jhanders34** [comment]
Using 1.7.0.Alpha12 and a snapshot version of the liberty arquillian plugin version 2.1.0, the CDI tests and Core Profile TCK tests are no longer failing with trying to find the servlet APIs when run with Open Liberty.  I am looking to have the liberty arquillian 2.1.0 version publish today or Monday so we do now have evidence that an arquillian plugin can be used to not depend on servlet so other vendor implementations can pass the Core Profile TCK if they do not expose the Servlet API.  The way that the arquillian rest protocol was written the URL to talk to the server is the same as the servlet one so there is limited changes needed in order to use the rest protocol because you do not need to use a RESTful Web Services client to talk to the server.

I am not sure if any updates are needed to the Core Profile TCK user guide at all for this issue.  I know that the Wildfly team was working on updating their plugin to use the new REST protocol instead of servlet as well.  Not sure if they made progress there or not.

**Comment by arjantijms** [comment]
This seems to be done. Shall we close this issue?

**Comment by jhanders34** [comment]
Yes with the latest changes that were done, this problem is resolved and @brideck should be able to close it.  Liberty doesn't enable servlet for Core Profile testing and was able to certify without using the arquillian servlet runner.

**Comment by brideck** [comment]
Yep, my apologies. Closing as long-since resolved.
