### ISSUE TITLE
Core Profile TCK runner should exclude additional test groups from RESTful WS TCK

### ISSUE THREAD

**Issue by brideck** [jakartaee/platform-tck#1097]
Two new exclusion groups ('servlet' and 'security') have been proposed in the RESTful WS TCK:
https://github.com/jakartaee/rest/issues/1120
https://github.com/jakartaee/rest/issues/1121

If/when these are adopted and implemented, the Core Profile TCK in this project should be updated to exclude them.

**Comment by alwin-joseph** [comment]
New TCK bundle is generated at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-restful-ws-tck-3.1.1.zip with the new test groups - 'servlet' and 'security'.

**Comment by alwin-joseph** [comment]
Closing the issue as the exclude group was used in core profile TCK using https://github.com/jakartaee/platform-tck/commit/99969bfa4f3aac6fa4cb933358bd85f870c3460e.
