### ISSUE TITLE
Refactor a small number of `jaxrs` (EE mode) tests.

### ISSUE THREAD

**Issue by alwin-joseph** [jakartaee/platform-tck#1156]
The changes to convert the jaxrs tests to use arquillian were made using commit : https://github.com/jakartaee/platform-tck/commit/732c21e0919650cd170bb3ed3528f76577889c55. 

Unfortunately I did commit directly to the tckrefactor branch accidentally and I do not have a PR for reviewing. I will use this issue to describe the changes and track further related changes in jaxrs module. Please suggest if there is any better way to address this.
 
The changes in https://github.com/jakartaee/platform-tck/commit/732c21e0919650cd170bb3ed3528f76577889c55 : 

- The common changes that were made in https://github.com/jakartaee/platform-tck/pull/912 is also used but not committed to the repository. Will wait for the PR for same. eg the common/pom.xml and pom.xml file changes are expected from the PR.
- Sample tck runner is created at glassfish-runner/jaxrs-platform-tck to run the tests against glassfish.
- Had to duplicate below glassfish related files for convenience. Once the glassfishtck module is compiled these can be removed and used from that module. Currently glassfishtck module is commented at root pom.xml and does not compile. 
  -jaxrs/src/main/java/com/sun/ts/tests/jaxrs/lib/implementation/sun/common/SunRIURL.java
  -jaxrs/src/main/java/com/sun/ts/tests/jaxrs/lib/implementation/sun/jersey/TSWebConfiguration.java

Current status : 

All 138 tests in jaxrs module passes with Glassfish 7.0.0-M10

cc @scottmarlow @gurunrao @olamy

**Comment by olamy** [comment]
@alwin-joseph I'm definitely happy to merge https://github.com/jakartaee/platform-tck/pull/912 to the branch https://github.com/jakartaee/platform-tck/tree/tckrefactor

**Comment by gurunrao** [comment]
refactor of JAXRS is complete.
