### ISSUE TITLE
Jaxrs Web Profile keyword is not recognised 

### ISSUE THREAD

**Issue by simonladen** [jakartaee/platform-tck#1167]
**Describe the bug**
Running the JAXRS TCK tests with the web profile, having the keyword "jaxrs_web_profile" set up is not enough to run the tests in that suite.

**To Reproduce**
1. Run the JAXRS suite, with profile = WEB, and keywords including jaxrs_web_profile (but not "all" or "jaxrs")
2. When initialising the run, the script inspects the keywords, and skips running the tests altogether

A workaround is to use the keyword "jaxrs" to run this suite

**Expected behavior**
according to src/com/sun/ts/lib/harness/keyword.properties, "jaxrs_web_profile" should be a keyword as valid as "jaxrs" to run the tests in com/sun/ts/tests/jaxrs (it should allow any of these keywords "jaxrs","javaee","jaxrs_web_profile","javaee_web_profile")

Attached: console output with 2 sets of keywords:
[run_with_keyword_jaxrs_web_profile.txt](https://github.com/jakartaee/platform-tck/files/11344458/run_with_keyword_jaxrs_web_profile.txt) uses the keywords:
javaee_web_profile|jacc_web_profile|jaspic_web_profile|javamail_web_profile|connector_web_profile|**jaxrs_web_profile**
--> The tests are not run after the setup.
[run_with_keyword_jaxrs.txt](https://github.com/jakartaee/platform-tck/files/11344459/run_with_keyword_jaxrs.txt) uses the keywords:
javaee_web_profile|jacc_web_profile|jaspic_web_profile|javamail_web_profile|connector_web_profile|**jaxrs**|**jaxrs_web_profile**
--> The tests are run successfully

**Comment by gurunrao** [comment]
Issue has been raised for legacy TCK. Community will not do any more development using legacy sources for EE 11+. we need to fix with refactored source for EE 11, and has been fixed with refactored source, hence I will mark as closed.
