### ISSUE TITLE
 ClassLoader issue in embedded Arquillian #1178

### ISSUE THREAD

**Issue by jbescos** [jakartaee/platform-tck#1187]
**Describe the bug**

This issue happens when you run Arquillian tests within the same JVM.

`getClass().getResourceAsSream()` will look for resources in the maven configured path:  `/target/classes` and `/target/test-classes`. The resource `/key.pub` will not be there, because it exists in the web application classpath, making the test to fail.

It is possible to handle this scenario obtaining the class loader in this way, because the Arquillian extension can set a different class loader:
`ClassLoader classLoader = Thread.currentThread().getContextClassLoader();`

**To Reproduce**
Run ee.jakarta.tck.core.rest.jsonb.cdi.CustomJsonbSerializationIT with Helidon

**Expected behavior**
Test should pass

**Additional information**
This a duplicate of https://github.com/helidon-io/helidon/issues/6884
The purpose of this is that we need an issue here to be bundled with core-profile
This was already solved here: https://github.com/jakartaee/platform-tck/pull/1178

**Comment by scottmarlow** [comment]
Now that this is a TCK challenge for EE 10, please describe why the https://github.com/jakartaee/platform-tck/pull/1178 change is needed.  There are a lot of details in https://github.com/helidon-io/helidon/issues/6884 but I would like to see more information in this challenge about why the test needs to change.

Question about https://github.com/jakartaee/platform-tck/pull/1178, should that be changed to handle null being returned from Thread.currentThread().getContextClassLoader()?  If null is returned, the previous code `getClass().getResourceAsStream` could be used.

**Comment by jbescos** [comment]
Hi @scottmarlow , I have updated this issue with more information, and I created a new PR https://github.com/jakartaee/platform-tck/pull/1188 for the null check.

**Comment by scottmarlow** [comment]
Closing as accepted as per previous comment
