### ISSUE TITLE
[tck-challege] Jakarta EE Core TCK's cdi-lite-tck-suite.xml out of sync with CDI's tck-tests.xml

### ISSUE THREAD

**Issue by jamezp** [jakartaee/platform-tck#1196]
**Relevant Information**

1. The relevant specification version and section number(s).
    - Jakarta EE 10 Core Profile
2. The coordinates of the challenged test(s).
    - `jakarta.ee.tck.coreprofile:cdi-lite-tck-suite:10.0.1` 
3. The exact TCK version.
    - 10.0.1
4. The implementation being tested, including name and company.
    - WildFly by Red Hat
5. A full description of why the test is invalid and what the correct behavior is believed to be.
    - There are 3 CDI tests that should be excluded from the Jakarta EE Core TCK's CDI Lite TCK that are not:
        - `org.jboss.cdi.tck.tests.implementation.simple.lifecycle.SimpleBeanLifecycleTest`
        - `org.jboss.cdi.tck.tests.context.DestroyForSameCreationalContextTest`
        - `org.jboss.cdi.tck.tests.definition.bean.types.ManagedBeanTypesTest`
6. Any supporting material; debug logs, test output (.jtr file), test logs, run scripts, etc.

The [`cdi-lite-tck-suite.xml`](https://github.com/jakartaee/platform-tck/blob/82a976ee03a7ea47bcd8ff8623579708802e937f/core-profile-tck/cdi-tck-suite/src/main/resources/cdi-lite-tck-suite.xml) is out of sync with CDI's [`tck-tests.xml`](https://github.com/jakartaee/cdi-tck/blob/0c25a2d9cd8206cf7ff30184884e6ce062fb3176/impl/src/main/resources/tck-tests.xml#L18). These tests should be excluded in the `cdi-lite-tck-suite.xml`:
```xml
<!-- https://github.com/jakartaee/cdi-tck/issues/453 -->
<class name="org.jboss.cdi.tck.tests.implementation.simple.lifecycle.SimpleBeanLifecycleTest">
    <methods>
        <exclude name="testCreateReturnsSameBeanPushed"/>
    </methods>
</class>
<class name="org.jboss.cdi.tck.tests.context.DestroyForSameCreationalContextTest">
    <methods>
        <exclude name="testDestroyForSameCreationalContextOnly"/>
    </methods>
</class>

<!-- https://github.com/jakartaee/cdi-tck/issues/485 -->
<class name="org.jboss.cdi.tck.tests.definition.bean.types.ManagedBeanTypesTest">
    <methods>
        <exclude name=".*"/>
    </methods>
</class>
```

The latter (`org.jboss.cdi.tck.tests.definition.bean.types.ManagedBeanTypesTest`) causes issues with the TCK passing on Java 21.

If we cannot get this merged and a new Jakarta EE 10 Core Profile TCK released, we're asking that we can explicitly exclude these tests in our test configuration. In our case it will be on the `maven-surefire-plugin` section of our `pom.xml` for the CDI Lite TCK tests.

**Additional context**
The CDI TCK Challenge issues:
- https://github.com/jakartaee/cdi-tck/issues/483
- https://github.com/jakartaee/cdi-tck/issues/485

**Comment by jamezp** [comment]
I seem to be wrong about being able to use excludes in the `maven-surefire-plugin` as the tests use TestNG and the `suiteXmlFiles` configuration parameter. With that set, the `excludes` are ignored. We'd need to modify the `cdi-lite-tck-suite.xml` to get this working. This is definitely possible, but a new release of the Jakarta EE 10 Core Profile would be preferred.

**Comment by scottmarlow** [comment]
Thanks @jamezp

**Comment by scottmarlow** [comment]
The initial Core Profile 10.0.3 TCK is staged at http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl//jakarta-core-profile-tck-10.0.3.zip
