### ISSUE TITLE
TCK Challenge : Servlet URLClient getRequestedSessionIdTest1 test involving session management using URL rewriting doesn't provide option to enable URL rewriting

### ISSUE THREAD

**Issue by ankedia** [jakartaee/platform-tck#1201]
Specification: Servlet session management using URL rewriting .
Assertion: [Servlet:JAVADOC:559](https://github.com/jakartaee/platform-tck/blob/master/internal/docs/servlet/Servlet2.4JavadocAssertions.xml#L6500)

1. The relevant specification version and section number(s).
https://jakarta.ee/specifications/platform/9

2. The coordinates of the challenged test(s).
[com/sun/ts/tests/servlet/api/jakarta_servlet_http/httpservletrequest/URLClient.java#getRequestedSessionIdTest1](https://github.com/jakartaee/platform-tck/blob/9.1.x/src/com/sun/ts/tests/servlet/api/jakarta_servlet_http/httpservletrequest/URLClient.java)
com/sun/ts/tests/servlet/api/jakarta_servlet_http/httpservletrequest/URLClient.java#getRequestedSessionIdTest2
com/sun/ts/tests/servlet/api/jakarta_servlet_http/httpservletrequestwrapper/URLClient.java#getRequestedSessionIdTest1
com/sun/ts/tests/servlet/api/jakarta_servlet_http/httpservletrequestwrapper/URLClient.java#getRequestedSessionIdTest2

3 The exact TCK version.
 https://download.eclipse.org/jakartaee/platform/9.1/jakarta-jakartaeetck-9.1.0.zip

4. The implementation being tested, including name and company.
Weblogic Server / Oracle

5. A full description of why the test is invalid and what the correct behavior is believed to be.

The tests mentioned above verify session management in Servlet using URL rewriting (encoding the URL with session-id). In the WebLogic server,  the URL rewriting is disabled by default for newer applications where the schema version of web.xml is higher than or equal to 3.1. 

For older versions of applications with a schema version of web.xml less than 3.1, it is enabled by default. 

The URL rewriting can be enabled in the WebLogic server by setting  “url-rewriting-enable” to true in "weblogic.xml". The test assumes that URL rewriting is enabled by default and is not portable (or depends on a particular implementation). Currently there is no way to override the “url-rewriting-enable” property as the test application doesn't provide a "sun-web.xml" file.

6 Any supporting material; debug logs, test output (.jtr file), test logs, run scripts, etc.
Will provide test run logs or output for these tests very soon.

**Additional context**
Suggesting to provide a sun-web.xml with "enableURLRewriting" set to true. The WebLogic porting layer can then override the corresponding value of "url-rewriting-enable” to true in "weblogic.xml".  Currently there is no way to override the value of "url-rewriting-enable” flag (which is set to "false" by default).

**Comment by markt-asf** [comment]
I'm minded to reject this challenge.
Providing, and documenting, appropriate configuration to pass the TCK is a container responsibility, not a TCK responsibility.

**Comment by ankedia** [comment]
[test_log.txt](https://github.com/jakartaee/platform-tck/files/13339496/test_log.txt)

**Comment by ankedia** [comment]
cc @alwin-joseph . @markt-asf As I mentioned in the description, these tests are not portable or depends on a particular implementation. For other tests where a container-specific configuration needs to be provided to pass the TCK, the TCK provides a corresponding "sun-web.xml" file. If it's not possible to provide this file, then these tests should be excluded. I'll also discuss with my colleauges to get their opinions and provide an update here.

**Comment by markt-asf** [comment]
The test is fully portable since it uses only the Servlet API. That a container has chosen to implement a non-specification compliant default that in turn causes a TCK failure is entirely the responsibility of the container.

The TCK has no visibility of container configuration options nor their defaults. It is simply not possible for the TCK to know what configuration each container may require to pass the TCK.

The only practical approach is the one currently adopted. Containers are responsible for determining, and documenting, container specific configuration required to pass the TCK,

**Comment by ankedia** [comment]
> That a container has chosen to implement a non-specification compliant default that in turn causes a TCK failure is entirely the responsibility of the container.
My understanding is that the specification doesn't specify the default. However, we have decided to use the container specific configuration to make the TCK tests pass. I will close this issue.
