### ISSUE TITLE
TCK failures with refactored JSP TCK

### ISSUE THREAD

**Issue by markt-asf** [jakartaee/platform-tck#1233]
**Describe the bug**
I am observing multiple failures when testing a local build of the refactored JSP TCK built from source.

**To Reproduce**
1. Build the JSP TCK from source using the tckrefactor branch
2. Run it against Apache Tomcat using this repo: https://github.com/apache/tomcat-tck
3. Observe multiple failures

**Expected behavior**
The TCK to pass in full or any failures to be traceable to Tomcat bugs.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Ubuntu 22.04.4 LTS

I have a PR to address all but one of these failures that I'll provide shortly.

The remaining failure I do not know how to address.
The failing test is the `tldResourcePathJsp11Test` in the `com.sun.ts.tests.jsp.spec.tldres` package. The test fails because it expects a taglibrary to be built and packaged in `/WEB-INF/lib/multitaglib.jar` which doesn't happen.

**Comment by alwin-joseph** [comment]
The current JSP TCK from tckrefactor branch has a tckrunner with Glassfish at https://github.com/jakartaee/platform-tck/tree/tckrefactor/glassfish-runner/jsp-tck, it does passes all the jsp tests where the host and port is injected by arquillian container and not from system properties.

> The failing test is the `tldResourcePathJsp11Test` in the `com.sun.ts.tests.jsp.spec.tldres` package. The test fails because it expects a taglibrary to be built and packaged in `/WEB-INF/lib/multitaglib.jar` which doesn't happen.

We do create the jar at https://github.com/jakartaee/platform-tck/blob/da90b3cb2709d0507b59eedfc990dfee069eca23/jsp/src/main/java/com/sun/ts/tests/jsp/spec/tldres/URLClientIT.java#L87 and add it to the jsp_tldres_web.war. Will check again if any tld is missing.

**Comment by alwin-joseph** [comment]
> 
> > The failing test is the `tldResourcePathJsp11Test` in the `com.sun.ts.tests.jsp.spec.tldres` package. The test fails because it expects a taglibrary to be built and packaged in `/WEB-INF/lib/multitaglib.jar` which doesn't happen.
> 
> We do create the jar at
> 
> https://github.com/jakartaee/platform-tck/blob/da90b3cb2709d0507b59eedfc990dfee069eca23/jsp/src/main/java/com/sun/ts/tests/jsp/spec/tldres/URLClientIT.java#L87
> and add it to the jsp_tldres_web.war. Will check again if any tld is missing.

One issue as I see is that at https://github.com/jakartaee/platform-tck/blob/da90b3cb2709d0507b59eedfc990dfee069eca23/jsp/src/main/java/com/sun/ts/tests/jsp/spec/tldres/URLClientIT.java#L90C108-L90C114 multi2.tld is being added twice, but shouldn't cause any error IMO.

**Comment by markt-asf** [comment]
Thanks for merging #1234. I can confirm I just see this single error now with testing with the latest JSP TCK and Tomcat 11.0.x. I'm currently looking into why Tomcat doesn't see the JAR that is created.

**Comment by markt-asf** [comment]
Closing this as the remaining issue is a Tomcat issue.
