### ISSUE TITLE
WebSocket TCK 2.2.0 zip is incorrect

### ISSUE THREAD

**Issue by jansupol** [jakartaee/platform-tck#1275]
The staged TCK https://www.eclipse.org/downloads/download.php?file=/ee4j/jakartaee-tck/jakartaee11/staged/eftl/jakarta-websocket-tck-2.2.0.zip is incorrect:

- The WebSocket-TCK-2.2.0.pom contains a reference on a SNAPSHOT
```
    <parent>
        <groupId>jakarta.tck</groupId>
        <artifactId>project</artifactId>
        <version>11.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
```
- The Zip file does not contain jakarta.tck.project.pom at all

**Comment by gurunrao** [comment]
fixed by https://github.com/jakartaee/platform-tck/pull/1276
