### ISSUE TITLE
WebSocket 2.2.0 TCK is STILL incorrect

### ISSUE THREAD

**Issue by jansupol** [jakartaee/platform-tck#1279]
`websocket-tck\artifacts\websocket-tck-2.2.0.pom` contains:
```
 <properties>
        <jakarta.ee.version>11.0.0-SNAPSHOT</jakarta.ee.version>
```
Hence it requires:
- jakarta.tck:common:jar:11.0.0-SNAPSHOT
- jakarta.tck:libutil:jar:11.0.0-SNAPSHOT
- jakarta.tck:signaturetest:jar:11.0.0-SNAPSHOT
- jakarta.tck:runtime:jar:11.0.0-SNAPSHOT

**Comment by gurunrao** [comment]
thanks for the WebSocket TCK review @jansupol  . WebSocket TCK dependency on common TCK artifacts is a known issue as described in the comment - https://github.com/jakartaee/websocket/issues/423#issuecomment-2028017277.
@scottmarlow is making progress with publish of M1 version of the above mentioned artifacts to maven repository.
