### ISSUE TITLE
Jacc code can be removed from the platform TCK

### ISSUE THREAD

**Issue by arjantijms** [jakartaee/platform-tck#1286]
We ported the JACC TCK code to the standalone Jakarta Authorization TCK at:

https://github.com/jakartaee/authorization/tree/master/tck

So this means the JACC code within the standalone can be removed.

**Comment by scottmarlow** [comment]
Sounds like the https://github.com/jakartaee/platform-tck/tree/tckrefactor/jacc folder should be removed then since EJB Embedded was removed for Jakarta EE 10 (meaning there are no `jacc` tests that to run as part of the Platform TCK.

**Comment by arjantijms** [comment]
Everything done
