### ISSUE TITLE
Use Maven Wrapper

### ISSUE THREAD

**Issue by sebersole** [jakartaee/platform-tck#1288]
**Is your feature request related to a problem? Please describe.**

At the moment, the TCK requires a local download and install of Maven to run. 

**Describe the solution you'd like**

Would be better to offer the [Maven Wrapper](https://maven.apache.org/wrapper/)

**Additional context**

Would also love to get this into the Standalone Persistence TCK as well - https://github.com/jakartaee/persistence/issues/616

**Comment by scottmarlow** [comment]
Closing as the pull request was merged.  Thanks @sebersole for the change!
