### ISSUE TITLE
Remove optional TCK tests from the EE 11 Platform TCK

### ISSUE THREAD

**Issue by scottmarlow** [jakartaee/platform-tck#1296]
https://github.com/jakartaee/jakartaee-api/issues/162 is for removing optional SPEC API from the jakarta-api to cover the [EE 11 release plan changes](https://jakarta.ee/specifications/platform/11/):
> Removals, deprecations or backwards incompatible changes
>
>  -  Prune ManagedBeans
>  -  Remove all use of SecurityManager
>  -  Remove all optional specifications
 

The Platform TCK should also remove any optional tests for EE 11.  Removed tests could be moved to a different repository but I don't think the EE 11 release plans require that to happen as of now.

CC @brideck

**Comment by edburns** [comment]
Hello @starksm64  and @scottmarlow , for someone to pick this up, can you please clarify that the repo to which the ultimate PR that fixes this will be directed is https://github.com/jakartaee/platform-tck? If not that, then whare?

**Comment by edburns** [comment]
- The tests to be removed are in the `tckrefactor` branch.
- Move the removed tests to a new branch. Call it `platform-tck-12-removed-tests`.
- The set of tests to be moved aside is recorded at https://github.com/jakartaee/platform-tck/issues/1352.
