### ISSUE TITLE
Refactor the TCK repo to maintain the optional tests being removed from EE 11

### ISSUE THREAD

**Issue by starksm64** [jakartaee/platform-tck#1342]
**Is your feature request related to a problem? Please describe.**
The TCK tests for optional specifications are not required to be run for EE 11, and so we may not be porting them to the Arquillian/JUnit5 framework. 

**Describe the solution you'd like**
We should decide how to refactor the TCK repo to preserve these tests as some form of JavaTest/CTS legacy bundle for people to use. Maybe a EE11-legacy-optional branch that removes all tests that have been ported over would be a good approach.

sub-jira tasks:
- [x] #1352
- [ ] move SOAP with Attachments tests into a new location.
- [x] move XML Binding tests into a new location.

**Comment by scottmarlow** [comment]
> Maybe a EE11-legacy-optional branch that removes all tests that have been ported over would be a good approach.

It might be confusing to mention `EE11` in the branch name for removed tests (since the removed tests are not part of EE 11).  Perhaps a shorter name like `legacy` could be used.

We could later add other tests there as well from other earlier EE releases.

We might want to consider storing extracted binary images of certain TCK archives as well if that might be easier to maintain instead of building (legacy) TCKs from source in the future.

**Comment by gurunrao** [comment]
> **Is your feature request related to a problem? Please describe.** The TCK tests for optional specifications are not required to be run for EE 11, and so we may not be porting them to the Arquillian/JUnit5 framework.
> 
> **Describe the solution you'd like** We should decide how to refactor the TCK repo to preserve these tests as some form of JavaTest/CTS legacy bundle for people to use. Maybe a EE11-legacy-optional branch that removes all tests that have been ported over would be a good approach.
> 
> sub-jira tasks:
> 
>     * [ ]  [move Web Services (e.g.  Enterprise Web Services,  Web Services Metadata, XML Web Services) tests into a new location. #1352](https://github.com/jakartaee/platform-tck/issues/1352)
> 
>     * [ ]  move SOAP with Attachments tests into a new location.
> 
>     * [ ]  move XML Binding tests into a new location.

XML binding test reside at repository https://github.com/jakartaee/jaxb-tck, hence no move to new location is required.

**Comment by scottmarlow** [comment]
> XML binding test reside at repository https://github.com/jakartaee/jaxb-tck, hence no move to new location is required.

@gurunrao good point.  Also, it looks like all of the TCK test source references to jakarta.xml.bind are contained in web services tests that will be moved.
