### ISSUE TITLE
Need to generate and move parameterized source into the source modules

### ISSUE THREAD

**Issue by starksm64** [jakartaee/platform-tck#1349]
**Is your feature request related to a problem? Please describe.**
The tckrefactor branch has vehicle related test classes that are processed as templates to generate source in the test package, and then compiled, bunded into test artifact, and then deleted. This does not work with modern test frameworks that expect all source to be in the test packages.

**Describe the solution you'd like**
All of the paramterized test source and descriptors need to be placed into the java and resource paths of the testsuite.

**Additional context**
Currently identified classes and descriptors include:
common/src/main/java/com/sun/ts/tests/common/vehicle/ejbliteservlet2/ejbliteservlet2_vehicle_web.xml
common/src/main/java/com/sun/ts/tests/common/vehicle/ejbliteservlet2/EJBLiteServlet2Filter.java.txt
common/src/main/java/com/sun/ts/tests/common/vehicle/ejblitejsp/EJBLiteJSPTag.java.txt
common/src/main/java/com/sun/ts/tests/common/vehicle/ejblitesecuredjsp/ejblitesecuredjsp.tld
common/src/main/java/com/sun/ts/tests/common/vehicle/ejblitesecuredjsp/EJBLiteSecuredJSPTag.java.txt
common/src/main/java/com/sun/ts/tests/common/vehicle/ejbliteservlet/ejbliteservlet_vehicle_web.xml
common/src/main/java/com/sun/ts/tests/common/vehicle/ejbliteservlet/EJBLiteServletVehicle.java.txt
common/src/main/java/com/sun/ts/tests/common/vehicle/ejbliteservlet/HttpServletDelegate.java.txt
common/src/main/java/com/sun/ts/tests/common/vehicle/ejbliteservletcal/ejbliteservletcal_vehicle_web.xml
common/src/main/java/com/sun/ts/tests/common/vehicle/ejbliteservletcal/EJBLiteServletContextAttributeListener.java.txt

I think @scottmarlow has identified other areas that are doing build time transformations of template files as well.

**Comment by scottmarlow** [comment]
https://gist.github.com/scottmarlow/fc5c8be4fb4b69b50bfb1423218b8c5d contains the list of various files that contain `@...@` parameters that are resolved via ant scripting.  We will not use Ant scripting in EE 11 so the other template files not addressed by the pull request need to be addressed (note that the [list](https://gist.github.com/scottmarlow/fc5c8be4fb4b69b50bfb1423218b8c5d ) should be updated after removing optional specification tests).

**Comment by starksm64** [comment]
I added your comment to the #1361 issue that is about dealing with the other template files.

**Comment by starksm64** [comment]
These tld files still need to be done:
common/src/main/java/com/sun/ts/tests/common/vehicle/ejblitejsp/ejblitejsp.tld
common/src/main/java/com/sun/ts/tests/common/vehicle/ejblitesecuredjsp/ejblitesecuredjsp.tld
