### ISSUE TITLE
move Web Services (e.g.  Enterprise Web Services,  Web Services Metadata, XML Web Services) tests into a new location.

### ISSUE THREAD

**Issue by scottmarlow** [jakartaee/platform-tck#1352]
This is a subtask for parent https://github.com/jakartaee/platform-tck/issues/1342. The goal is to move the Web Services tests out of the [platform-tck/tree/tckrefactor branch](https://github.com/jakartaee/platform-tck/tree/tckrefactor) as per what is decided in the parent https://github.com/jakartaee/platform-tck/issues/1342.

**Comment by edburns** [comment]
Also need to move aside the XML binding tests.

**Comment by scottmarlow** [comment]
> Also need to move aside the XML binding tests.

I  checked the output of `grep -rli jakarta.xml.bind --include=*.java` and XML Binding is only used in Web Services tests.

**Comment by edburns** [comment]
Scheduled to meet at 09:00 20240717.

**Comment by scottmarlow** [comment]
> Hello @scottmarlow , when you say "a new location" do you know what that is? Or is the real task to figure that out? I looked in #1342, but it is not clear to me where this new location is.

The new location is the newly created `[legacytck](https://github.com/jakartaee/platform-tck/tree/)` branch which currently contained a copy of the `tckrefactor` branch before the web services tests were removed.  A todo will be removing duplicate test sources from the legacytck branch and other work to make the TCK tests work.
