### ISSUE TITLE
Remove the use of the SecurityManager from the TCK

### ISSUE THREAD

**Issue by starksm64** [jakartaee/platform-tck#1359]
**Is your feature request related to a problem? Please describe.**
Related to the platform [SecurityManager Removal Epic](https://github.com/jakartaee/platform/issues/551), we need to remove the SecurityManager usage from the TCK codebase.

**Describe the solution you'd like**
All references and uses of the `java.lang.SecurityManager` need to be removed.

**Existing Uses**
[security-manager.txt](https://github.com/user-attachments/files/16169951/security-manager.txt)

**Comment by edburns** [comment]
Please confirm this sketch for how a new helper could complete the task.

1. Learn how to run the Jakarta 10 TCK against GlassFish 7.
2. Ensure it runs successfully, including the code to be removed under this issue.
3. Perform the removal action.
4. Ensure it still runs successfully.

Also, please confirm the changes for this issue should be made to the master branch of https://github.com/jakartaee/platform-tck .
