### ISSUE TITLE
Deal with other template files

### ISSUE THREAD

**Issue by starksm64** [jakartaee/platform-tck#1360]
Related to #1349, there are other template source files in the tckrefactor branch that need to be expanded into proper descriptors and source files:

```
[starksm@scottryzen sms-platform-tck]$ find . -name '*.template'
./ejb30/src/main/java/com/sun/ts/tests/ejb30/assembly/appres/appclientejb/application.xml.template
./ejb30/src/main/java/com/sun/ts/tests/ejb30/assembly/appres/warejb/application.xml.template
./ejb30/src/main/java/com/sun/ts/tests/ejb30/assembly/appres/warmbean/application.xml.template
./ejb30/src/main/java/com/sun/ts/tests/ejb30/bb/async/singleton/annotated/sun-ejb-jar.xml.template
./ejb30/src/main/java/com/sun/ts/tests/ejb30/bb/async/singleton/metadata/sun-ejb-jar.xml.template
./ejb30/src/main/java/com/sun/ts/tests/ejb30/bb/async/stateful/annotated/sun-ejb-jar.xml.template
./ejb30/src/main/java/com/sun/ts/tests/ejb30/bb/async/stateful/metadata/sun-ejb-jar.xml.template
./ejb30/src/main/java/com/sun/ts/tests/ejb30/bb/async/stateless/annotated/sun-ejb-jar.xml.template
./ejb30/src/main/java/com/sun/ts/tests/ejb30/bb/async/stateless/metadata/sun-ejb-jar.xml.template
./ejb30/src/main/java/com/sun/ts/tests/ejb30/bb/session/stateful/concurrency/accesstimeout/annotated/sun-ejb-jar.xml.template
./ejb30/src/main/java/com/sun/ts/tests/ejb30/bb/session/stateful/concurrency/metadata/annotated/sun-ejb-jar.xml.template
./ejb30/src/main/java/com/sun/ts/tests/ejb30/bb/session/stateful/timeout/annotated/sun-ejb-jar.xml.template
./ejb30/src/main/java/com/sun/ts/tests/ejb30/bb/session/stateful/timeout/descriptor/sun-ejb-jar.xml.template
./ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/async/singleton/annotated/sun-ejb-jar.xml.template
./ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/async/singleton/metadata/sun-ejb-jar.xml.template
./ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/async/stateful/annotated/sun-ejb-jar.xml.template
./ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/async/stateful/metadata/sun-ejb-jar.xml.template
./ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/async/stateless/annotated/sun-ejb-jar.xml.template
./ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/async/stateless/metadata/sun-ejb-jar.xml.template
./ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/packaging/war/datasource/global/Client.java.template
./ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/packaging/war/datasource/global/DataSourceBean.java.template
./ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/packaging/war/datasource/singleton/Client.java.template
./ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/packaging/war/datasource/singleton/DataSourceBean.java.template
./ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/packaging/war/datasource/singleton/DataSourceMBean.java.template
./ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/packaging/war/datasource/singleton/DataSourceRepeatableBean.java.template
./ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/packaging/war/datasource/singleton/JsfClient.java.template
./ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/packaging/war/datasource/stateful/ejb-jar.xml.template
./ejb30/src/main/java/com/sun/ts/tests/ejb30/misc/datasource/appclientejb/Client.java.template
./ejb30/src/main/java/com/sun/ts/tests/ejb30/misc/datasource/appclientejb/DataSourceBean.java.template
./ejb30/src/main/java/com/sun/ts/tests/ejb30/misc/datasource/twojars/ejb3_misc_datasource_twojars_client.xml.template
./ejb30/src/main/java/com/sun/ts/tests/ejb30/misc/datasource/twojars/two_standalone_component_ejb.xml.template
./ejb30/src/main/java/com/sun/ts/tests/ejb30/misc/datasource/twowars/DataSourceBean.java.template
./ejb30/src/main/java/com/sun/ts/tests/ejb30/misc/datasource/twowars/TestServlet.java.template
./ejb30/src/main/java/com/sun/ts/tests/ejb30/misc/datasource/twowars/TestServlet2.java.template
./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/jaxrs21/platform/providers/jsonb/web.xml.template
./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/jaxrs21/platform/providers/jsonp/web.xml.template
./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/platform/beanvalidation/annotation/web.xml.template
./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/platform/beanvalidation/constraintviolationexceptionmapper/web.xml.template
./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/platform/beanvalidation/validationexceptionmapper/web.xml.template
./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/platform/container/asyncresponse/web.xml.template
./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/platform/container/completioncallback/web.xml.template
./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/platform/ejbsingleton/web.xml.template
./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/platform/ejbstateless/web.xml.template
./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/platform/environment/servlet/web.xml.template
./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/platform/managedbean/web.xml.template
./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/platform/provider/jsonp/web.xml.template
```

**Comment by starksm64** [comment]
Adding comment from @scottmarlow  on issue #1349 

https://gist.github.com/scottmarlow/fc5c8be4fb4b69b50bfb1423218b8c5d contains the list of various files that contain @...@ parameters that are resolved via ant scripting. We will not use Ant scripting in EE 11 so the other template files not addressed by the pull request need to be addressed (note that the [list](https://gist.github.com/scottmarlow/fc5c8be4fb4b69b50bfb1423218b8c5d) should be updated after removing optional specification tests).

**Comment by alwin-joseph** [comment]
> ./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/jaxrs21/platform/providers/jsonb/web.xml.template
> ./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/jaxrs21/platform/providers/jsonp/web.xml.template
> ./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/platform/beanvalidation/annotation/web.xml.template
> ./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/platform/beanvalidation/constraintviolationexceptionmapper/web.xml.template
> ./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/platform/beanvalidation/validationexceptionmapper/web.xml.template
> ./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/platform/container/asyncresponse/web.xml.template
> ./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/platform/container/completioncallback/web.xml.template
> ./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/platform/ejbsingleton/web.xml.template
> ./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/platform/ejbstateless/web.xml.template
> ./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/platform/environment/servlet/web.xml.template
> ./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/platform/managedbean/web.xml.template
> ./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/platform/provider/jsonp/web.xml.template

The web.xml.template files above in jaxrs module are used by replacing the `servlet_adaptor` [text](https://github.com/jakartaee/platform-tck/blob/a17f63f97ab2404fe8337cb59bf6ca069cfb9831/jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/platform/beanvalidation/annotation/web.xml.template#L23) (corresponding to `servlet-class`) in them as it is done [here](https://github.com/jakartaee/platform-tck/blob/a17f63f97ab2404fe8337cb59bf6ca069cfb9831/jaxrs/src/main/java/com/sun/ts/tests/jaxrs/platform/beanvalidation/annotation/JAXRSClientIT.java#L63) and renaming them to web.xml.

The value of `servletAdaptor` class is obtained from a system property "servlet_adaptor" from [here](https://github.com/jakartaee/platform-tck/blob/a17f63f97ab2404fe8337cb59bf6ca069cfb9831/jaxrs/src/main/java/com/sun/ts/tests/jaxrs/common/JAXRSCommonClient.java#L197), which would need to be documented.

Do we need to change any of this ?

**Comment by starksm64** [comment]
> > ./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/jaxrs21/platform/providers/jsonb/web.xml.template
> > ./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/jaxrs21/platform/providers/jsonp/web.xml.template
> > ./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/platform/beanvalidation/annotation/web.xml.template
> > ./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/platform/beanvalidation/constraintviolationexceptionmapper/web.xml.template
> > ./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/platform/beanvalidation/validationexceptionmapper/web.xml.template
> > ./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/platform/container/asyncresponse/web.xml.template
> > ./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/platform/container/completioncallback/web.xml.template
> > ./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/platform/ejbsingleton/web.xml.template
> > ./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/platform/ejbstateless/web.xml.template
> > ./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/platform/environment/servlet/web.xml.template
> > ./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/platform/managedbean/web.xml.template
> > ./jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/platform/provider/jsonp/web.xml.template
> 
> The web.xml.template files above in jaxrs module are used by replacing the `servlet_adaptor` [text](https://github.com/jakartaee/platform-tck/blob/a17f63f97ab2404fe8337cb59bf6ca069cfb9831/jaxrs/src/main/resources/com/sun/ts/tests/jaxrs/platform/beanvalidation/annotation/web.xml.template#L23) (corresponding to `servlet-class`) in them as it is done [here](https://github.com/jakartaee/platform-tck/blob/a17f63f97ab2404fe8337cb59bf6ca069cfb9831/jaxrs/src/main/java/com/sun/ts/tests/jaxrs/platform/beanvalidation/annotation/JAXRSClientIT.java#L63) and renaming them to web.xml.
> 
> The value of `servletAdaptor` class is obtained from a system property "servlet_adaptor" from [here](https://github.com/jakartaee/platform-tck/blob/a17f63f97ab2404fe8337cb59bf6ca069cfb9831/jaxrs/src/main/java/com/sun/ts/tests/jaxrs/common/JAXRSCommonClient.java#L197), which would need to be documented.
> 
> Do we need to change any of this ?

That looks like it might just be fine.
