### ISSUE TITLE
Classes in signaturetest module needed in test archive are not public

### ISSUE THREAD

**Issue by starksm64** [jakartaee/platform-tck#1365]
**Describe the bug**
While testing the signaturetest module porting, I ran across the following three classes that need to be placed into the test archive, that are not public:

                com.sun.ts.tests.signaturetest.PackageList.class,
                com.sun.ts.tests.signaturetest.SignatureTestDriver.SignatureFileInfo.class,
                com.sun.ts.tests.signaturetest.javaee.JavaEESigTest.Containers.class,

**Expected behavior**
These need to be public in order to be visible to the StrinkWrap layer that builds the test archive.

**Comment by edburns** [comment]
Hello @starksm64, can you please point to an existing commit that shows something similar to this?

**Comment by starksm64** [comment]
The changes on #1367 show the changes
