### ISSUE TITLE
Refactor jstl (EE mode) tests.

### ISSUE THREAD

**Issue by starksm64** [jakartaee/platform-tck#1376]

**Comment by alwin-joseph** [comment]
- JSTL TCK tests has been refactored  via https://github.com/jakartaee/platform-tck/pull/1203 
- The TCK runner is created at glassfish-runner/jstl-tck : 541 tests pass with Glassfish 8.0.0-JDK17-M5
- Test fixes and other changes were included in below PRs : 
https://github.com/jakartaee/platform-tck/pull/1302
https://github.com/jakartaee/platform-tck/pull/1303
https://github.com/jakartaee/platform-tck/pull/1329
https://github.com/jakartaee/platform-tck/pull/1507
