### ISSUE TITLE
Refactor jaxws (EE mode) tests.

### ISSUE THREAD

**Issue by starksm64** [jakartaee/platform-tck#1382]

**Comment by scottmarlow** [comment]
@gurunrao the web services (including jaxws) tests were removed from the `main` branch on https://github.com/jakartaee/platform-tck.  Is there anything else that needs to be removed for web services?

**Comment by gurunrao** [comment]
> @gurunrao the web services (including jaxws) tests were removed from the `main` branch on https://github.com/jakartaee/platform-tck. Is there anything else that needs to be removed for web services?

I found references to webservices which will be used by refactored Platform TCK as follows: 

- Platform TCK documentation
-  lib/schemas/ directory
- ts.jte configuration file required for JavaTest Protocol

**Comment by gurunrao** [comment]
> > @gurunrao the web services (including jaxws) tests were removed from the `main` branch on https://github.com/jakartaee/platform-tck. Is there anything else that needs to be removed for web services?
> 
> I found references to webservices which will be used by refactored Platform TCK as follows:
> 
>     * Platform TCK documentation
> 
>     * lib/schemas/ directory
> 
>     * ts.jte configuration file required for JavaTest Protocol

Above mentioned changes are not needed, as per my knowledge, Hence will close the issue.
