### ISSUE TITLE
We need to switch the default branch to main on github

### ISSUE THREAD

**Issue by starksm64** [jakartaee/platform-tck#1394]
**Describe the bug**
We have renamed the tckrefactor branch main to reflect that is where development is happening, but we still have the old master branch as the default

**Comment by pzygielo** [comment]
I suppose this might be done with the PR to modify https://github.com/jakartaee/.eclipsefdn/blob/04391cf0caa40cab7a98d23aa0dd2e7d0895b375/otterdog/jakartaee.jsonnet#L1233

**Comment by starksm64** [comment]
OK, thanks, done here:

https://github.com/jakartaee/.eclipsefdn/pull/8

**Comment by starksm64** [comment]
This has been done.
