### ISSUE TITLE
Restore the jpa-platform test usage of the ServiceEETest class

### ISSUE THREAD

**Issue by starksm64** [jakartaee/platform-tck#1418]

**Comment by scottmarlow** [comment]
This makes sense also, will give this a shot.

**Comment by scottmarlow** [comment]
For reference, in EE 10, I think there are around 10,989 tests that WildFly runs for Platform TCK testing.

**Comment by scottmarlow** [comment]
Looks like we do need to process the JavaDoc entries also when parsing Java comments.

**Comment by scottmarlow** [comment]
With a change to also parse Javadoc comments the count of processed persistence tests is `2177` which may be correct as we are generating around 1294 new test files each of which is dedicated for a specific vehicle.

From a further check of the generated JPA source files, we have 10794 new tests that are tagged as @Test which is close to the `10989` test count mentioned above.  So, we can proceed forward now.

**Comment by scottmarlow** [comment]
https://github.com/eclipse-ee4j/jakartaee-tck-tools/issues/84 addressed ^ test count concern.

**Comment by scottmarlow** [comment]
The jpa/** tests were changed to (indirectly) extend the ServiceEETest class.  The jpa-tck/** tests were created which do not extend the ServiceEETest classes.
