### ISSUE TITLE
Refactor ejb30 (EE mode) tests.

### ISSUE THREAD

**Issue by starksm64** [jakartaee/platform-tck#1436]

**Comment by starksm64** [comment]
Some tests will need to be hand ported as they use custom ant scripts. Examples include:

- [ ] com.sun.ts.tests.ejb30.assembly.initorder.appclientejb uses two ejb jars with custom ejb30/common/twojars-import.xml

**Comment by arjantijms** [comment]
Tests have been refactored and are running: https://ci.eclipse.org/jakartaee-tck/view/EFTL-Certification-Jobs-11/job/11/job/standalone-tck/job/jakarta-enterprise-beans-tck-glassfish/
