### ISSUE TITLE
Refactor javaee (EE mode) tests

### ISSUE THREAD

**Issue by starksm64** [jakartaee/platform-tck#1480]

**Comment by alwin-joseph** [comment]
- Javaee module is refactored using https://github.com/jakartaee/platform-tck/pull/1205
- Other PRs to fix the tests and other changes are 
https://github.com/jakartaee/platform-tck/pull/1306 
https://github.com/jakartaee/platform-tck/pull/1508
- All the 24 tests pass with glassfish 8
