### ISSUE TITLE
compilation failures due to ManagedBean

### ISSUE THREAD

**Issue by gurunrao** [jakartaee/platform-tck#1545]
files having dependency on ManagedBean :
- ejb30/src/main/java/com/sun/ts/tests/ejb30/misc/moduleName/appclientejb/ModuleMBean.java
- ejb30/src/main/java/com/sun/ts/tests/ejb30/misc/moduleName/appclientejb/ModuleMBean.java
- ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/packaging/war/mbean/interceptor/lifecyclecdi/
- ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/packaging/war/mbean/interceptor/lifecyclecdi/
- ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/packaging/war/mbean/interceptor/lifecyclecdi/
- ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/packaging/war/mbean/interceptor/lifecyclecdi/OverrideWithPostConstructBean.java
- ejb30/src/main/java/com/sun/ts/tests/ejb30/assembly/mbean/appclient/OneManagedBean.java
- ejb30/src/main/java/com/sun/ts/tests/ejb30/misc/moduleName/twojars/ModuleMBean.java
- ejb30/src/main/java/com/sun/ts/tests/ejb30/misc/moduleName/twojars/ModuleMBean.java
- ejb30/src/main/java/com/sun/ts/tests/ejb30/misc/moduleName/twowars/ModuleMBean.java
- ejb30/src/main/java/com/sun/ts/tests/ejb30/misc/moduleName/twowars/ModuleMBean.java 
- ejb30/src/main/java/com/sun/ts/tests/ejb30/assembly/mbean/appclient/TwoManagedBean.java
- ejb30/src/main/java/com/sun/ts/tests/ejb30/assembly/mbean/appclient/TwoManagedBean.java
- ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/packaging/war/mbean/interceptor/lifecycle/AManagedBean.java
- ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/packaging/war/mbean/interceptor/lifecycle/AManagedBean.java
- ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/packaging/war/mbean/interceptor/business/InterceptorBean.java
- ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/packaging/war/mbean/interceptor/business/InterceptorBean.java
- ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/packaging/war/mbean/interceptor/business/InterceptorOverrideBean.java
- ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/packaging/war/mbean/interceptor/business/InterceptorOverrideBean.java
- ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/packaging/war/mbean/interceptor/business/InterceptorOverride34Bean.java
- ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/packaging/war/mbean/interceptor/business/InterceptorOverride34Bean.java
- ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/packaging/war/mbean/interceptor/lifecycle/InterceptorOverride34Bean.java
- ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/packaging/war/mbean/interceptor/lifecycle/InterceptorOverride34Bean.java
- ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/packaging/war/mbean/interceptor/lifecycle/InterceptorBean.java
- ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/packaging/war/mbean/interceptor/lifecycle/InterceptorBean.java
- ejb30/src/main/java/com/sun/ts/tests/ejb30/assembly/appres/common/AppResManagedBean.java
- ejb30/src/main/java/com/sun/ts/tests/ejb30/assembly/appres/common/AppResManagedBean.java
- ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/packaging/war/mbean/interceptor/lifecycle/InterceptorOverrideBean.java
- ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/packaging/war/mbean/interceptor/lifecycle/InterceptorOverrideBean.java
- ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/packaging/war/mbean/interceptor/invocationcontext/InvocationContextBean.java
- ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/packaging/war/mbean/interceptor/invocationcontext/InvocationContextBean.java
- ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/packaging/war/mbean/interceptor/invocationcontext/InvocationContextInterceptorBean.java
- ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/packaging/war/mbean/interceptor/invocationcontext/InvocationContextInterceptorBean.java
-

**Comment by gurunrao** [comment]
duplicate of - https://github.com/jakartaee/platform-tck/issues/1184

**Comment by scottmarlow** [comment]
I'll address the compile error by reverting to the older Annotations.

**Comment by gurunrao** [comment]
> @scottmarlow , @starksm64 @brideck - Are there any possibility of running above mentioned Test by removing ManagedBean or refactoring test to work without ManagedBean? If answer is `no`, shall I remove all the tests related to file mentioned above? CC: @edburns

@edburns - we need help from folks who are experts of EJB to know whether some of the tests mentioned can be refactored to not to use ManagedBean, TCK community will be deleting the tests if tests cannot be refactored.

**Comment by gurunrao** [comment]
closing the issue as https://github.com/jakartaee/platform-tck/pull/1558 resolves the same.
