### ISSUE TITLE
Shrinkwrap version increment to 3.3.1 seems to cause a test failure

### ISSUE THREAD

**Issue by scottmarlow** [jakartaee/platform-tck#1575]
Test failure is:

> [INFO] Running shrinkwrap.LibResolveTest
> Version URL: file:/home/smarlow/tck/platformtck/arquillian/javatest/target/classes/javatest.version
> Version info: 11.0.0-SNAPSHOT
> SLF4J: No SLF4J providers were found.
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
> [ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.065 s <<< FAILURE! - in shrinkwrap.LibResolveTest
> [ERROR] shrinkwrap.LibResolveTest.resolveProtocolLib Time elapsed: 0.039 s <<< ERROR!
> org.jboss.shrinkwrap.resolver.api.Invokable$InvocationException: Unable to invoke onlyOne([Ljava.lang.Class;@4fb3ee4e) on object org.jboss.shrinkwrap.resolver.spi.loader.ServiceRegistry with parameters [Ljava.lang.Object;@5d7148e2
>        at org.jboss.shrinkwrap.resolver.api.Invokable.invokeMethod(Invokable.java:109)
>        at org.jboss.shrinkwrap.resolver.api.ResolverSystemFactory.createFromUserView(ResolverSystemFactory.java:93)
>        at org.jboss.shrinkwrap.resolver.api.ResolverSystemFactory.createFromUserView(ResolverSystemFactory.java:54)
>        at org.jboss.shrinkwrap.resolver.api.Resolvers.use(Resolvers.java:75)
>        at org.jboss.shrinkwrap.resolver.api.maven.Maven.resolver(Maven.java:36)
>        at shrinkwrap.LibResolveTest.resolveProtocolLib(LibResolveTest.java:27)
>        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
>        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
>        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
> Caused by: java.lang.reflect.InvocationTargetException
>        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
>        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
>        at org.jboss.shrinkwrap.resolver.api.Invokable.invokeMethod(Invokable.java:100)
>        ... 8 more
> Caused by: java.lang.RuntimeException: Could not create new service instance
>        at org.jboss.shrinkwrap.resolver.spi.loader.SpiServiceLoader.createInstance(SpiServiceLoader.java:251)
>        at org.jboss.shrinkwrap.resolver.spi.loader.SpiServiceLoader.createInstances(SpiServiceLoader.java:211)
>        at org.jboss.shrinkwrap.resolver.spi.loader.SpiServiceLoader.all(SpiServiceLoader.java:79)
>        at org.jboss.shrinkwrap.resolver.spi.loader.SpiServiceLoader.onlyOne(SpiServiceLoader.java:85)
>        at org.jboss.shrinkwrap.resolver.spi.loader.ServiceRegistry.onlyOne(ServiceRegistry.java:102)
>        ... 13 more
> Caused by: java.lang.reflect.InvocationTargetException
>        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
>        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
>        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
>        at org.jboss.shrinkwrap.resolver.spi.loader.SpiServiceLoader.createInstance(SpiServiceLoader.java:247)
>        ... 17 more
> Caused by: java.lang.IllegalAccessError: class org.eclipse.aether.supplier.RepositorySystemSupplier tried to access method 'void org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.<init>(org.eclipse.aether.internal.impl.TrackingFileManager, org.
> eclipse.aether.impl.UpdatePolicyAnalyzer)' (org.eclipse.aether.supplier.RepositorySystemSupplier and org.eclipse.aether.internal.impl.DefaultUpdateCheckManager are in unnamed module of loader 'app')
>        at org.eclipse.aether.supplier.RepositorySystemSupplier.getUpdateCheckManager(RepositorySystemSupplier.java:173)
>        at eu.maveniverse.maven.mima.runtime.standalonestatic.MemoizingRepositorySystemSupplierLookup.getUpdateCheckManager(MemoizingRepositorySystemSupplierLookup.java:127)
>        at org.eclipse.aether.supplier.RepositorySystemSupplier.get(RepositorySystemSupplier.java:528)
>        at eu.maveniverse.maven.mima.runtime.standalonestatic.MemoizingRepositorySystemSupplierLookup.<init>(MemoizingRepositorySystemSupplierLookup.java:41)
>        at eu.maveniverse.maven.mima.runtime.standalonestatic.StandaloneStaticRuntime.createRepositorySystemLookup(StandaloneStaticRuntime.java:65)
>        at eu.maveniverse.maven.mima.runtime.standalonestatic.StandaloneStaticRuntime.create(StandaloneStaticRuntime.java:40)
>        at org.jboss.shrinkwrap.resolver.impl.maven.bootstrap.MavenRepositorySystem.getContext(MavenRepositorySystem.java:164)
>        at org.jboss.shrinkwrap.resolver.impl.maven.bootstrap.MavenRepositorySystem.<init>(MavenRepositorySystem.java:64)
>        at org.jboss.shrinkwrap.resolver.impl.maven.ConfigurableMavenWorkingSessionImpl.<init>(ConfigurableMavenWorkingSessionImpl.java:58)
>        at org.jboss.shrinkwrap.resolver.impl.maven.MavenWorkingSessionImpl.<init>(MavenWorkingSessionImpl.java:112)
>        at org.jboss.shrinkwrap.resolver.impl.maven.MavenResolverSystemImpl.<init>(MavenResolverSystemImpl.java:43)
>        ... 23 more
> 

Locally, the following change helps me to build:

```
diff --git a/pom.xml b/pom.xml
index 4a28cabdd..68f1cff3d 100644
--- a/pom.xml
+++ b/pom.xml
@@ -129,7 +129,7 @@
         <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
         <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
         <shrinkwrap.api.version>2.0.0-beta-1</shrinkwrap.api.version>
-        <shrinkwrap.version>3.3.1</shrinkwrap.version>
+        <shrinkwrap.version>3.3.0</shrinkwrap.version>
         <slf4j.version>2.0.0</slf4j.version>
         <surefire.failIfNoSpecifiedTests>false</surefire.failIfNoSpecifiedTests>
         <!-- Jakarta WebSocket -->

```

**Comment by starksm64** [comment]
The shrinkwrap dependencies are being overriden in the arquillian submodule as they had been set independently when it was in the jakarta-ee-tools repo. We need to reconcile the dependencies now that the arquillian/pom.xml is importing the platform-tck/pom.xml
