### ISSUE TITLE
Skip JDK setup + use of cts-trunk-almgit.properties file if they do not exist

### ISSUE THREAD

**Issue by scottmarlow** [jakartaee/platform-tck#7]
I tried using the docker/build_cts8.sh script locally and hacked past assumptions of the JDK location and file cts-trunk-almgit.properties.  My changes are in [https://github.com/scottmarlow/jakartaee-tck/tree/skipsome](https://github.com/scottmarlow/jakartaee-tck/tree/skipsome) but aren't ready for a pull request as I don't know how to handle the absence of cts-trunk-almgit.properties.  I'm creating this issue as a tracker, so others can see my branch, in case they try to do the same as I have.  

I understand that all of this is still being worked on.  After addressing the above issues, I then hit [missing jars issue](https://github.com/eclipse-ee4j/jakartaee-tck/issues/4).

**Comment by anajosep** [comment]
The missing libraries are included now. The README.md file contains wiki [link(](https://github.com/eclipse-ee4j/jakartaee-tck/wiki/Instructions-for-building-and-running-JakartaEE-TCK-bundle) which details the steps to build and run Jakarta EE TCK bundle from scratch.  The build/run scripts have been modified as well. Can you try out the steps and let me know if you still face any issue building it ?

**Comment by scottmarlow** [comment]
I'm getting the following build error:

> /mnt/hudson_workspace/workspace/jakartaee-ee8/buildcts/docker/build_jakartaeetck.sh
+ BUILD_WORKSPACE=/mnt/hudson_workspace/workspace/jakartaee-ee8/buildcts
+ export ANT_HOME=/usr/share/ant/
+ ANT_HOME=/usr/share/ant/
+ export JAVA_HOME=/opt/jdk1.8.0_171
+ JAVA_HOME=/opt/jdk1.8.0_171
+ export PATH=/opt/jdk1.8.0_171/bin:/usr/share/ant//bin:/qa/tools/opt/x86_64/jdk1.8.0_151/bin:/usr/local/bin:/usr/bin
+ PATH=/opt/jdk1.8.0_171/bin:/usr/share/ant//bin:/qa/tools/opt/x86_64/jdk1.8.0_151/bin:/usr/local/bin:/usr/bin
+ cd /mnt/hudson_workspace/workspace/jakartaee-ee8/buildcts
++ pwd
+ export BASEDIR=/mnt/hudson_workspace/workspace/jakartaee-ee8/buildcts
+ BASEDIR=/mnt/hudson_workspace/workspace/jakartaee-ee8/buildcts
+ which ant
/usr/share/ant/bin/ant
+ ant -version
Error: JAVA_HOME is not defined correctly.
  We cannot execute /opt/jdk1.8.0_171/bin/java

Should we update the $WORKSPACE/docker/build_jakartaeetck.sh script to check if JAVA_HOME is already defined, instead of assuming  /opt/jdk1.8.0_171/bin/java?

Another approach could be to only use /opt/jdk1.8.0_171 if it exists:
`if [ -d /opt/jdk1.8.0_171 ]; then
  export JAVA_HOME=/opt/jdk1.8.0_171
  export PATH=$JAVA_HOME/bin:$PATH
fi
`
Should do the same for ANT_HOME as well.

**Comment by anajosep** [comment]
The hardcoded paths need to be modified. These scripts were initially meant to be run from with the docker container - anajosep/cts-base:0.1. I need to modify it for taking these values from the env rather than having hardcoded paths. I will do the required changes.

**Comment by ggam** [comment]
I confirm I'm able to build it overriding to my actual paths. Awesome job, @anajosep! Now time to run the tests.
