### ISSUE TITLE
eftl-standalonetck-certification completely fails

### ISSUE THREAD

**Issue by arjantijms** [jakartaee/platform-tck#794]
The Standalone certification job at https://ci.eclipse.org/jakartaee-tck/view/EPL-EFTL-CERTIFICATION-JOBS/job/eftl-standalonetck-certification/ currently completely fails, out of the thousands of tests not a singe one passes.

This is likely to do with this job already assuming "glassfish7", while it should still use "glassfish6" (or maybe there should be a new switch, or a separate set of jobs).

Note that the current choices in the main job are:

```
EFTL_JAKARTAEE91_PROMOTED
EFTL_JAKARTAEE9_PROMOTED
EFTL_JAKARTAEE91_STAGED
EFTL_JAKARTAEE91_BUILD_LATEST
```

This one would not expect this to trigger Jakarta EE 10 / GlassFish 7.

**Comment by alwin-joseph** [comment]
https://github.com/eclipse-ee4j/jakartaee-tck/issues/837#issuecomment-1041525907 .
