### ISSUE TITLE
eftl-standalonetck-certification completely fails 2

### ISSUE THREAD

**Issue by arjantijms** [jakartaee/platform-tck#837]
All Jakarta EE tests in the standalone TCK currently fail with:

```
[javatest.batch] com.sun.ts.lib.deliverable.PropertyNotSetException: No value found for jimage.dir.  Please check your jte file for an appropiate value
[javatest.batch] 	at com.sun.ts.lib.deliverable.AbstractPropertyManager.getProperty(AbstractPropertyManager.java:214)
[javatest.batch] 	at com.sun.ts.lib.harness.TSScript.run(TSScript.java:237)
[javatest.batch] 	at com.sun.javatest.Script.run(Script.java:241)
[javatest.batch] 02-12-2022 13:08:59:  Harness - harness.executeMode is set to "2"	at com.sun.javatest.DefaultTestRunner.runTest(DefaultTestRunner.java:174)
```

**Comment by alwin-joseph** [comment]
The test run scripts were updated to start using Glassfish 7 (glassfish7 as parent folder) . Are you looking to run Jakarta 9 TCKs using glassfish 6 ?

**Comment by alwin-joseph** [comment]
I have created separate eftl-standalonetck-certification jobs for JakartaEE 10 (https://ci.eclipse.org/jakartaee-tck/job/10/job/eftl-standalonetck-certification/) and JakartaEE 9.1(https://ci.eclipse.org/jakartaee-tck/job/9.1/job/eftl-standalonetck-certification/) releases.

I might have to make some amends with the parameters and configs but it should work for please feel free to try out. Please let us know if something fails. I believe glassfish CI have had the certification jobs copied over too. Ideally for pre-JakartaEE10 it would be better to use those jobs for certifying glassfish.

It is hard to modify the https://ci.eclipse.org/jakartaee-tck/job/eftl-standalonetck-certification/ job to allow multiple releases of TCKs to be run.
