### ISSUE TITLE
Extract EJB Lite tests in platform TCK into a standalone TCK

### ISSUE THREAD

**Issue by alwin-joseph** [jakartaee/platform-tck#963]
**Is your feature request related to a problem? Please describe.**
Need to extract EJB lite tests (src/com/sun/ts/tests/ejb30/lite & src/com/sun/ts/tests/ejb32/lite) into a new standalone TCK so these tests can be executed easily.

**Describe the solution you'd like**
 Create a standalone TCK (named say * ejblite-tck *) with only src/com/sun/ts/tests/ejb30/lite & src/com/sun/ts/tests/ejb32/lite .

**Additional context**
Also create a new runner script that is similar to tck run scripts at https://github.com/eclipse-ee4j/glassfish/tree/master/appserver/tests/tck.

Also discussed at 

https://github.com/eclipse-ee4j/jakartaee-tck/pull/962#issuecomment-1120244992

https://github.com/eclipse-ee4j/jakartaee-tck/pull/962#issuecomment-1121331951

@arjantijms @scottmarlow

**Comment by alwin-joseph** [comment]
> For now having a bundle and run it like e.g. https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/docker/jacctck.sh would be a great start.

I have made some progress towards this. I will create a draft PR soon with the changes I have now.

**Comment by scottmarlow** [comment]
Removed `EE10` label as the work is not planned to be included for `EE 10`

**Comment by arjantijms** [comment]
Maybe we can retarget this to EE 12?

**Comment by scottmarlow** [comment]
The task will likely be done during the EE 12 release but might use the EE 10 Platform TCK source.

**Comment by arjantijms** [comment]
This seems to be implicitely done by refactoring for EE 11. The EJB runner for GlassFish (and other servers) could now be set to only run the lite tests.
